# Generated by Django 5.2 on 2025-05-08 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('organizer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('batting_style', models.CharField(choices=[('R', 'Right-handed'), ('L', 'Left-handed')], max_length=20)),
                ('bowling_style', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_role', models.CharField(choices=[('BAT', 'Batsman'), ('BOWL', 'Bowler'), ('AR', 'All-Rounder'), ('WK', 'Wicket Keeper')], max_length=4)),
                ('player_class', models.CharField(max_length=20)),
                ('year_joined', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('match_type', models.CharField(choices=[('TOURNAMENT', 'Tournament'), ('FRIENDLY', 'Friendly')], max_length=20)),
                ('match_format', models.CharField(choices=[('T20', 'Twenty20'), ('ODI', 'One Day (50 Overs)'), ('TEST', 'Test Match')], default='T20', max_length=4)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('ananda_extras_byes', models.IntegerField(default=0, verbose_name='Byes')),
                ('ananda_extras_leg_byes', models.IntegerField(default=0, verbose_name='Leg Byes')),
                ('opponent_extras_byes', models.IntegerField(default=0, verbose_name='Opponent Byes')),
                ('opponent_extras_leg_byes', models.IntegerField(default=0, verbose_name='Opponent Leg Byes')),
                ('man_of_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricket_stats.player')),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('INJURY', 'Injury'), ('TACTICAL', 'Tactical'), ('OTHER', 'Other')], max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('substitution_time', models.CharField(max_length=50)),
                ('approved_by', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_stats.match')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_in', to='cricket_stats.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_out', to='cricket_stats.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=20)),
                ('coach', models.CharField(max_length=100)),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of', to='cricket_stats.player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_stats.team'),
        ),
        migrations.CreateModel(
            name='TeamStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
                ('matches_drawn', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('net_run_rate', models.FloatField(default=0.0)),
                ('position', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_stats.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_stats.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricket_stats.tournament'),
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField(choices=[(1, 'First Innings'), (2, 'Second Innings')], default=1)),
                ('batting_order', models.IntegerField(blank=True, null=True)),
                ('runs_scored', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('how_out', models.CharField(blank=True, max_length=100, null=True)),
                ('overs_bowled', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('wickets_taken', models.IntegerField(default=0)),
                ('maidens', models.IntegerField(default=0)),
                ('wide_balls', models.IntegerField(default=0)),
                ('no_balls', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('stumpings', models.IntegerField(default=0)),
                ('runouts', models.IntegerField(default=0)),
                ('is_playing_xi', models.BooleanField(default=True)),
                ('is_substitute', models.BooleanField(default=False)),
                ('is_century', models.BooleanField(default=False)),
                ('is_half_century', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_stats.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_stats.player')),
            ],
            options={
                'ordering': ['innings', 'batting_order'],
                'unique_together': {('match', 'player', 'innings')},
            },
        ),
    ]
