# Generated by Django 5.2 on 2025-04-09 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('match_type', models.CharField(choices=[('TOURNAMENT', 'Tournament'), ('FRIENDLY', 'Friendly')], max_length=20)),
                ('toss_winner', models.CharField(max_length=100)),
                ('toss_decision', models.CharField(choices=[('BAT', 'Bat'), ('BOWL', 'Bowl')], max_length=10)),
                ('result', models.CharField(choices=[('WON', 'Won'), ('LOST', 'Lost'), ('DRAW', 'Draw')], max_length=10)),
                ('ananda_score', models.CharField(max_length=50)),
                ('opponent_score', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('scorecard_photo', models.ImageField(blank=True, null=True, upload_to='scorecards/')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('organizer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('batting_style', models.CharField(choices=[('R', 'Right-handed'), ('L', 'Left-handed')], max_length=20)),
                ('bowling_style', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_role', models.CharField(choices=[('BAT', 'Batsman'), ('BOWL', 'Bowler'), ('AR', 'All-Rounder'), ('WK', 'Wicket Keeper')], max_length=4)),
                ('player_class', models.CharField(max_length=20)),
                ('year_joined', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_order', models.IntegerField(blank=True, null=True)),
                ('runs_scored', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('how_out', models.CharField(blank=True, max_length=50, null=True)),
                ('overs_bowled', models.FloatField(default=0)),
                ('runs_conceded', models.IntegerField(default=0)),
                ('wickets_taken', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('stumpings', models.IntegerField(default=0)),
                ('runouts', models.IntegerField(default=0)),
                ('is_playing_xi', models.BooleanField(default=True)),
                ('is_substitute', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_stats.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_stats.player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='man_of_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricket_stats.player'),
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('INJURY', 'Injury'), ('TACTICAL', 'Tactical'), ('OTHER', 'Other')], max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('substitution_time', models.CharField(max_length=50)),
                ('approved_by', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_stats.match')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_in', to='cricket_stats.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_out', to='cricket_stats.player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=20)),
                ('coach', models.CharField(max_length=100)),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of', to='cricket_stats.player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_stats.team'),
        ),
        migrations.CreateModel(
            name='TeamStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.IntegerField(default=0)),
                ('matches_won', models.IntegerField(default=0)),
                ('matches_lost', models.IntegerField(default=0)),
                ('matches_drawn', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('net_run_rate', models.FloatField(default=0.0)),
                ('position', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_stats.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricket_stats.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cricket_stats.tournament'),
        ),
    ]
