# Generated by Django 5.2 on 2025-05-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchplayer',
            options={'ordering': ['innings', 'batting_order']},
        ),
        migrations.RemoveField(
            model_name='match',
            name='ananda_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opponent_score',
        ),
        migrations.AddField(
            model_name='match',
            name='ananda_extras_byes',
            field=models.IntegerField(default=0, verbose_name='Byes'),
        ),
        migrations.AddField(
            model_name='match',
            name='ananda_extras_leg_byes',
            field=models.IntegerField(default=0, verbose_name='Leg Byes'),
        ),
        migrations.AddField(
            model_name='match',
            name='ananda_extras_no_balls',
            field=models.IntegerField(default=0, verbose_name='No Balls'),
        ),
        migrations.AddField(
            model_name='match',
            name='ananda_extras_penalty',
            field=models.IntegerField(default=0, verbose_name='Penalty Runs'),
        ),
        migrations.AddField(
            model_name='match',
            name='ananda_extras_wides',
            field=models.IntegerField(default=0, verbose_name='Wides'),
        ),
        migrations.AddField(
            model_name='match',
            name='ananda_first_innings_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='ananda_second_innings_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_test_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='match_format',
            field=models.CharField(choices=[('T20', 'Twenty20'), ('ODI', 'One Day'), ('TEST', 'Test Match'), ('OTHER', 'Other Format')], default='T20', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_extras_byes',
            field=models.IntegerField(default=0, verbose_name='Opponent Byes'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_extras_leg_byes',
            field=models.IntegerField(default=0, verbose_name='Opponent Leg Byes'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_extras_no_balls',
            field=models.IntegerField(default=0, verbose_name='Opponent No Balls'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_extras_penalty',
            field=models.IntegerField(default=0, verbose_name='Opponent Penalty Runs'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_extras_wides',
            field=models.IntegerField(default=0, verbose_name='Opponent Wides'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_first_innings_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_second_innings_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='overs_per_innings',
            field=models.IntegerField(default=20, help_text='Number of overs per innings (leave blank for Test matches)'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='innings',
            field=models.IntegerField(choices=[(1, 'First Innings'), (2, 'Second Innings')], default=1),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='is_century',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='is_half_century',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='no_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='wide_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='matchplayer',
            unique_together={('match', 'player', 'innings')},
        ),
    ]
