# Generated by Django 5.2 on 2025-05-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_stats', '0002_alter_matchplayer_options_remove_match_ananda_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='ananda_extras_byes',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ananda_extras_leg_byes',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ananda_extras_no_balls',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ananda_extras_penalty',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ananda_extras_wides',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ananda_first_innings_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ananda_second_innings_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='is_test_match',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opponent_extras_byes',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opponent_extras_leg_byes',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opponent_extras_no_balls',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opponent_extras_penalty',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opponent_extras_wides',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opponent_first_innings_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opponent_second_innings_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='overs_per_innings',
        ),
        migrations.AlterField(
            model_name='match',
            name='match_format',
            field=models.CharField(choices=[('T20', 'Twenty20'), ('ODI', 'One Day International'), ('TEST', 'Test Match')], default='T20', max_length=4),
        ),
    ]
