# Generated by Django 5.2 on 2025-05-18 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_stats', '0002_add_match_formats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchformat',
            name='days',
        ),
        migrations.AddField(
            model_name='match',
            name='match_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Number of days for the match (2 or 3 for multi-day matches)'),
        ),
        migrations.CreateModel(
            name='PlayerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], default='P', max_length=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('time_reported', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='cricket_stats.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='cricket_stats.player')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Player Attendance',
                'ordering': ['match__match_date', 'player__first_name'],
                'unique_together': {('player', 'match')},
            },
        ),
    ]
