# Generated by Django 5.2 on 2025-05-18 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_stats', '0003_remove_matchformat_days_match_match_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchplayer',
            options={'ordering': ['match', 'innings_number', 'batting_order']},
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='catches',
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='is_substitute',
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='maidens',
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='missed_catches',
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='runouts',
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='selection_notes',
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='stumpings',
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='wide_balls',
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bowled_players', to='cricket_stats.player'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='fielder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fielded_players', to='cricket_stats.player'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='is_keeper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='maidens_bowled',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='wides',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='is_playing_xi',
            field=models.BooleanField(default=False),
        ),
    ]
