# Generated by Django 5.2 on 2025-05-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_stats', '0002_add_selection_notes'),
        ('cricket_stats', '0003_update_matchplayer'),
    ]

    operations = [
    ]
