# Generated by Django 5.2 on 2025-05-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_stats', '0003_remove_match_ananda_extras_byes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='scorecard_photo',
        ),
        migrations.RemoveField(
            model_name='match',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='match',
            name='toss_decision',
        ),
        migrations.RemoveField(
            model_name='match',
            name='toss_winner',
        ),
        migrations.AddField(
            model_name='match',
            name='ananda_extras_byes',
            field=models.IntegerField(default=0, verbose_name='Byes'),
        ),
        migrations.AddField(
            model_name='match',
            name='ananda_extras_leg_byes',
            field=models.IntegerField(default=0, verbose_name='Leg Byes'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_extras_byes',
            field=models.IntegerField(default=0, verbose_name='Opponent Byes'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_extras_leg_byes',
            field=models.IntegerField(default=0, verbose_name='Opponent Leg Byes'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='maidens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_format',
            field=models.CharField(choices=[('T20', 'Twenty20'), ('ODI', 'One Day (50 Overs)'), ('TEST', 'Test Match')], default='T20', max_length=4),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
