# Generated by Django 5.2 on 2025-05-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_stats', '0004_add_maidens_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='scorecard_photo',
        ),
        migrations.RemoveField(
            model_name='match',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='match',
            name='toss_decision',
        ),
        migrations.RemoveField(
            model_name='match',
            name='toss_winner',
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
