# Generated by Django 5.2 on 2025-05-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_stats', '0004_alter_matchplayer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='catches',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of catches taken'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='direct_hits',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of direct hit run outs'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='dropped_catches',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of catches dropped'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='run_outs',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of run outs effected'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='stumpings',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of stumpings (for wicket-keepers)'),
        ),
    ]
