# Generated by Django 5.2 on 2025-05-18 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_stats', '0005_matchplayer_catches_matchplayer_direct_hits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('fitness', 'Fitness Training'), ('cricket', 'Cricket Training')], max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training Session',
                'verbose_name_plural': 'Training Sessions',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='playerattendance',
            options={'ordering': ['training_session__date', 'player__first_name'], 'verbose_name_plural': 'Player Attendance'},
        ),
        migrations.AddField(
            model_name='playerattendance',
            name='arrival_time',
            field=models.TimeField(blank=True, help_text='Time player arrived at training', null=True),
        ),
        migrations.AddField(
            model_name='playerattendance',
            name='departure_time',
            field=models.TimeField(blank=True, help_text='Time player left training', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='playerattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='playerattendance',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='cricket_stats.trainingsession'),
        ),
        migrations.AlterUniqueTogether(
            name='playerattendance',
            unique_together={('player', 'training_session')},
        ),
        migrations.RemoveField(
            model_name='playerattendance',
            name='match',
        ),
    ]
