# Generated by Django 5.2 on 2025-05-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_stats', '0007_fix_team_foreign_key'),
    ]

    operations = [
        # Removed college_name and name fields since they already exist in the database
        migrations.AddField(
            model_name='match',
            name='team_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='cricket_stats.team'),
        ),
    ]
