# Generated by Django 5.2 on 2025-05-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_stats', '0008_match_college_name_match_name_match_team_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='college_name',
            field=models.CharField(default='Ananda College', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
