# Generated by Django 5.2 on 2025-05-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_stats', '0009_match_college_name_match_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='comments',
            field=models.TextField(blank=True, help_text='Comments about player selection or performance', null=True),
        ),
    ]
