# Generated by Django 5.2 on 2025-05-26 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_stats', '0005_update_tournament_fields'),
        ('cricket_stats', '0010_matchplayer_comments'),
    ]

    operations = [
    ]
